'use strict'

const EVENTS_TYPE_TOTAL_CHART = 'TOTAL_CHART'
const EVENTS_TYPE_AVERAGE_CHART = 'AVERAGE_CHART'
const EVENTS_TYPE_TOTAL_LIST = 'TOTAL_LIST'
const EVENTS_TYPE_AVERAGE_LIST = 'AVERAGE_LIST'

module.exports = {
	EVENTS_TYPE_TOTAL_CHART,
	EVENTS_TYPE_AVERAGE_CHART,
	EVENTS_TYPE_TOTAL_LIST,
	EVENTS_TYPE_AVERAGE_LIST
}