'use strict'

const SIZES_TYPE_BROWSER_HEIGHT = 'BROWSER_HEIGHT'
const SIZES_TYPE_BROWSER_RESOLUTION = 'BROWSER_RESOLUTION'
const SIZES_TYPE_BROWSER_WIDTH = 'BROWSER_WIDTH'
const SIZES_TYPE_SCREEN_HEIGHT = 'SCREEN_HEIGHT'
const SIZES_TYPE_SCREEN_RESOLUTION = 'SCREEN_RESOLUTION'
const SIZES_TYPE_SCREEN_WIDTH = 'SCREEN_WIDTH'

module.exports = {
	SIZES_TYPE_BROWSER_HEIGHT,
	SIZES_TYPE_BROWSER_RESOLUTION,
	SIZES_TYPE_BROWSER_WIDTH,
	SIZES_TYPE_SCREEN_HEIGHT,
	SIZES_TYPE_SCREEN_RESOLUTION,
	SIZES_TYPE_SCREEN_WIDTH
}