export const MODALS_DOMAIN_ADD = 'modals_domain_add'
export const MODALS_DOMAIN_EDIT = 'modals_domain_edit'
export const MODALS_EVENT_ADD = 'modals_event_add'
export const MODALS_EVENT_EDIT = 'modals_event_edit'
export const MODALS_PERMANENT_TOKEN_ADD = 'modals_permanent_token_add'
export const MODALS_PERMANENT_TOKEN_EDIT = 'modals_permanent_token_edit'