export const ROUTE_VIEWS = 'route_views'
export const ROUTE_PAGES = 'route_pages'
export const ROUTE_REFERRERS = 'route_referrers'
export const ROUTE_DURATIONS = 'route_durations'
export const ROUTE_LANGUAGES = 'route_languages'
export const ROUTE_SIZES = 'route_sizes'
export const ROUTE_OS = 'route_os'
export const ROUTE_SETTINGS = 'route_settings'